baseURL: "https://olalekan-soyewo.netlify.app/"
languageCode: "en-us"
title: "Olalekan Soyewo | ML Engineer & Software Developer"
theme: "portfolio-theme"

# Add these lines if they're not already present
contentDir: "content"
layoutDir: "layouts"

# Ensure the blog is not explicitly excluded
disableKinds: []



menu:
  main:
    - name: "About"
      url: "/#about"
      weight: 1
      params:
        mobileHide: true
    - name: "Projects"
      url: "/#projects"
      weight: 2
    - name: "Skills"
      url: "/#skills"
      weight: 3
    - name: "Blog"
      url: "/blog"
      weight: 4
    - name: "Experience"
      url: "/#experience"
      weight: 5
      params:
        mobileHide: true
    - name: "Contact"
      url: "/#contact"
      weight: 6
      

params:
  name: "Olalekan Soyewo"
  description: "ML Engineer & Software Developer"
  location: "Toronto, Canada"
  email: "paulsoyewo@gmail.com"
  linkedin: "https://www.linkedin.com/in/lekan-soyewo/"
  github: "https://github.com/sportynest"

